import { UploadedFile } from '../_models';
export class ExpenseRequest {
    expenseId: number;
    assignmentId: number;
    contractorName: string;
    contractorId: number;
    prepaidExpense: number;
    name: string;
    weekEnding: Date;
    projectName: string;
    mondayDate: Date;
    tuesdayDate: Date;
    wednesdayDate: Date;
    thursdayDate: Date;
    fridayDate: Date;
    saturdayDate: Date;
    sundayDate: Date;
    weeklyTotalExpense: number;
    expenseStatus: number;
    approveTime: Date;
    isReleased: boolean;
    isDraft: boolean;
    mondayHotel: number;
    mondayTravel: number;		
    mondayMarketing: number;
    mondayMiles: number;
    mondayMileage: number;
    mondayMeals: number;		
    mondayPhone: number;
    mondayOther: number;
    mondayExpenses: number;
    
    tuesdayHotel: number;
    tuesdayTravel: number;
    tuesdayMarketing: number;
    tuesdayMiles: number;
    tuesdayMileage: number;
    tuesdayMeals: number;		
    tuesdayPhone: number;
    tuesdayOther: number;
    tuesdayExpenses: number;

    wednesdayHotel: number;
    wednesdayTravel: number;
    wednesdayMarketing: number;
    wednesdayMiles: number;
    wednesdayMileage: number;
    wednesdayMeals: number;		
    wednesdayPhone: number;
    wednesdayOther: number;
    wednesdayExpenses: number;

    thursdayHotel: number;
    thursdayTravel: number;
    thursdayMarketing: number;
    thursdayMiles: number;
    thursdayMileage: number;
    thursdayMeals: number;		
    thursdayPhone: number;
    thursdayOther: number;
    thursdayExpenses: number;

    fridayHotel: number;
    fridayTravel: number;
    fridayMarketing: number;
    fridayMiles: number;
    fridayMileage: number;
    fridayMeals: number;		
    fridayPhone: number;
    fridayOther: number;
    fridayExpenses: number;

    saturdayHotel: number;
    saturdayTravel: number;
    saturdayMarketing: number;
    saturdayMiles: number;
    saturdayMileage: number;
    saturdayMeals: number;		
    saturdayPhone: number;
    saturdayOther: number;
    saturdayExpenses: number;
    
    sundayHotel: number;
    sundayTravel: number;
    sundayMarketing: number;
    sundayMiles: number;
    sundayMileage: number;
    sundayMeals: number;		
    sundayPhone: number;
    sundayOther: number;
    sundayExpenses: number;
    expenseAttachments: UploadedFile[];
}
