export const states = [
    { id: '', value: 'Select State' },
    { id: 'AA', value: 'Armed Forces Americas' },
    { id: 'AB', value: 'Alberta' },
    { id: 'AE', value: 'Armed Forces Europe' },
    { id: 'AK', value: 'Alaska' },
    { id: 'AL', value: 'Alabama' },
    { id: 'AP', value: 'Armed Forces Pacific' },
    { id: 'AR', value: 'Arkansas' },
    { id: 'AS', value: 'American Samoa' },
    { id: 'AZ', value: 'Arizona' },
    { id: 'BC', value: 'British Columbia' },
    { id: 'CA', value: 'California' },
    { id: 'CO', value: 'Colorado' },
    { id: 'CT', value: 'Connecticut' },
    { id: 'DC', value: 'District Of Columbia' },
    { id: 'DE', value: 'Delaware' },
    { id: 'FA', value: 'Foreign Address' },
    { id: 'FL', value: 'Florida' },
    { id: 'FM', value: 'Federated States Of Micronesia' },
    { id: 'GA', value: 'Georgia' },
    { id: 'GU', value: 'Guam' },
    { id: 'HI', value: 'Hawaii' },
    { id: 'IA', value: 'Iowa' },
    { id: 'ID', value: 'Idaho' },
    { id: 'IL', value: 'Illinois' },
    { id: 'IN', value: 'Indiana' },
    { id: 'KS', value: 'Kansas' },
    { id: 'KY', value: 'Kentucky' },
    { id: 'LA', value: 'Louisiana' },
    { id: 'MA', value: 'Massachusetts' },
    { id: 'MB', value: 'Manitoba' },
    { id: 'MD', value: 'Maryland' },
    { id: 'ME', value: 'Maine' },
    { id: 'MH', value: 'Marshall Islands' },
    { id: 'MI', value: 'Michigan' },
    { id: 'MN', value: 'Minnesota' },
    { id: 'MO', value: 'Missouri' },
    { id: 'MP', value: 'Northern Mariana Islands' },
    { id: 'MS', value: 'Mississippi' },
    { id: 'MT', value: 'Montana' },
    { id: 'NB', value: 'New Brunswick' },
    { id: 'NC', value: 'North Carolina' },
    { id: 'ND', value: 'North Dakota' },
    { id: 'NE', value: 'Nebraska' },
    { id: 'NF', value: 'Newfoundland' },
    { id: 'NH', value: 'New Hampshire' },
    { id: 'NJ', value: 'New Jersey' },
    { id: 'NM', value: 'New Mexico' },
    { id: 'NT', value: 'Northwest Territories' },
    { id: 'NV', value: 'Nevada' },
    { id: 'NY', value: 'New York' },
    { id: 'OH', value: 'Ohio' },
    { id: 'OK', value: 'Oklahoma' },
    { id: 'ON', value: 'Ontario' },
    { id: 'OR', value: 'Oregon' },
    { id: 'PA', value: 'Pennsylvania' },
    { id: 'PE', value: 'Prince Edward Island' },
    { id: 'PR', value: 'Puerto Rico' },
    { id: 'PW', value: 'Palau' },
    { id: 'QC', value: 'Quebec' },
    { id: 'RI', value: 'Rhode Island' },
    { id: 'SC', value: 'South Carolina' },
    { id: 'SD', value: 'South Dakota' },
    { id: 'SK', value: 'Saskatchewan' },
    { id: 'TN', value: 'Tennessee' },
    { id: 'TX', value: 'Texas' },
    { id: 'UT', value: 'Utah' },
    { id: 'VA', value: 'Virginia' },
    { id: 'VI', value: 'Virgin Islands' },
    { id: 'VT', value: 'Vermont' },
    { id: 'WA', value: 'Washington' },
    { id: 'WI', value: 'Wisconsin' },
    { id: 'WV', value: 'West Virginia' },
    { id: 'WY', value: 'Wyoming' },
    { id: 'YT', value: 'Yukon' }
];
